### ISSUE TITLE
Start app and tray icon

### ISSUE THREAD

**Issue by jeremycourtaban** [snapcrafters/yakyak#15]
Hello,
Since my last Ubuntu 18.04 update (2020-01-31) no window displayed when I start Yakyak.
System monitor show Yakyak process running.
I have to receive an Hangout message to display Yakyak window.
Even with the Yakyak window displayed I haven't Yakyak app tray icon (option enable).
And to finish, this week-end I was able to use Yakyak with these bugs but since this morning I can't send message.
So at this time the only thing which still work is the message reception that displayed Yakyak window.
I use Yakyak v1.5.4 installed from Ubuntu softwares.
I also tried to uninstall and reinstall Yakyak to solve these bugs but with no success.

**Comment by popey** [comment]
Thanks for filing the issue, but as this software is now abandoned, I'm going to close all issues and archive the project.
