### ISSUE TITLE
'Possible fatal error on main process...'

### ISSUE THREAD

**Issue by kaflex** [snapcrafters/yakyak#20]
Linux Mint 20 Cinnamon version 4.6.7 64bit.

I put my email and password, when it tries to connect I get the error 'Possible fatal error on main process.  Yakyak could stop working as expected.', then nothing, just a white screen.  I have uninstalled and re-installed from snap.
![yakyak](https://user-images.githubusercontent.com/4981904/99962466-3a1bac80-2d5e-11eb-9a90-091866f9839d.png)

**Comment by popey** [comment]
Thanks for filing the issue, but as this software is now abandoned, I'm going to close all issues and archive the project.
