### ISSUE TITLE
Version 1.5.2 was released

### ISSUE THREAD

**Issue by averissimo** [snapcrafters/yakyak#5]
Can you guys update the snap as this version implements Google's protocol change that render all previous version unusable.

Thanks!

**Comment by popey** [comment]
https://transfer.sh/Teh99/yakyak-pr6.snap - is the snap built above, and actually still segfaults. So looks like it's not fixed upstream yet.

**Comment by predragmandic** [comment]
> https://transfer.sh/Teh99/yakyak-pr6.snap - is the snap built above, and actually still segfaults. So looks like it's not fixed upstream yet.

They claim it's fixed: https://github.com/yakyak/yakyak/issues/978
Would you care to post your findings there?

**Comment by mstyles** [comment]
I'm having a bit of troubling following everything that's going on, but it kinda sounds like the 1.5.2 release was changed/updated and snap has yet to get the "new" 1.5.2. It seems one user tried updating the snap package but didn't have credentials: yakyak/yakyak/issues/979

**Comment by lparsons** [comment]
[v1.5.3](https://github.com/yakyak/yakyak/releases/tag/v1.5.3) has been released. Is it possible to get that version as a snap now? I'm happy to help with the effort, but would need some pointers regarding the process.

**Comment by popey** [comment]
I tried building a snap which used 1.5.3, but the snap segfaults, just as previous releases do. :(

I've made the changes here https://github.com/snapcrafters/yakyak/pull/7

This should build in travs and at the end make a snap you can manually install to test.

**Comment by lparsons** [comment]
@popey Not sure what is segfaulting, but that seems unique to the snap build. The upstream issue is not a segfault, but manifests as a hang on startup. Where can I find the 1.5.3. snap from travis to test?

**Comment by popey** [comment]
Once it finished building (it failed first run) successfully, there'll be a transfer.sh url at the bottom of the travis log from https://github.com/snapcrafters/yakyak/pull/7

**Comment by lparsons** [comment]
Looks like transfer.sh is dead... (or almost, I'm not able to get the download from https://transfer.sh/yUFwC/yakyak-pr7.snap at the moment)

* https://news.ycombinator.com/item?id=18331139
* https://github.com/dutchcoders/transfer.sh/issues/116

**Comment by popey** [comment]
Bah! Ok, we'll have to look for other places for it in the future. We can deal with that another day. 

I'm downloading the snap from transfer.sh now and will push it somewhere that has more than wet-string bandwidth shortly.

**Comment by popey** [comment]
https://people.canonical.com/~alan/yakyak-pr7.snap

**Comment by lparsons** [comment]
OK, great. (not sure how you got that though). So, what's the recommended way to test out this snap? I've never installed from a local file.

**Comment by lparsons** [comment]
Well, I used `sudo snap install yakyak-pr7.snap --dangerous`.

But still get segfault:
```
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
asking for login credentials
Segmentation fault (core dumped)
```

Downloading the `.deb` file, installing, and then running works fine:
```
hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
2018-11-14 13:36:44 INFO removing refresh token
connected 0
2018-11-14 13:36:44 INFO removing cookie store
asking for login credentials
```

Looks like an issue with gtk modules perhaps?

**Comment by popey** [comment]
Thanks.  suspect the upstream deb was built on something newer than Ubuntu 16.04. I'll have a fiddle here and see what I can do.

**Comment by popey** [comment]
@lparsons your feedback has been useful, thanks. Seems upstream bumped to a newer electron which necessetated me changing from the gtk2 launcher to the gtk3 one. I've build and tested and it works here. Once it builds and lands in the store I'll promote to the stable channel. Thanks again, and apologies for the inconvenience.

**Comment by lparsons** [comment]
Glad I could be of help. Thanks for sorting it out.

**Comment by averissimo** [comment]
Thanks @popey and @lparsons !

To clear up a few things we are changing a bit our release tags

* X.Y.Z being a stable release
* X.Y.Z+1-beta-rolling a rolling release that we update and ask the community to test.

No more "updated" releases and ambiguous naming.

If there is a big change I'll guess it will be named X.Y+1.Z-alpha-rolling then X.Y+1.Z-beta-rolling and then the actual stable release
